# Generated by Django 3.2.11 on 2022-04-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('username', models.CharField(max_length=24)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
